#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument

if [ $# -ne 2 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	for _ in {0..5}
	do
		ping "$1"
	done
fi
