#!/usr/bin/env bash
#  a Bash script that:
#+ Creates the file /var/run/myscript.pid containing its PID
#+ Displays To infinity and beyond indefinitely
#+ Displays I hate the kill command when receiving a SIGTERM signal
#+ Displays Y U no love me?! when receiving a SIGINT signal
#+ Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo touch /var/run/myscript.pid
echo "$$" > /var/run/myscript.pid

print_sigquit ()
{
	sudo rm /var/run/myscript.pid
	exit
}
trap print_sigquit SIGQUIT

print_sigterm ()
{
	echo "I hate the kill command"
	sudo rm /var/run/myscript.pid
	exit
}
trap print_sigterm SIGTERM

print_sigint ()
{
	echo "Y U no love me?!"
}
trap print_sigint SIGINT

while :
do
	echo "To infinity and beyond"
	sleep 2
done
