#!/usr/bin/env bash
#  that manages manage_my_process

case $1 in
    start)
        "./manage_my_process" &
        PID=$!
        echo $PID > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        PID=$(cat /var/run/my_process.pid)
        kill "$PID"
        sudo rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        PID=$(cat /var/run/my_process.pid)
        kill "$PID"
        sleep 1
        ./manage_my_process &
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
