#!/usr/bin/env bash
#  that manages manage_my_process

case $1 in
    start)
        ./100-process_and_pid_file &
        PID=$!
        echo $PID > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        PID=$(cat /var/run/my_process.pid)
        kill "$PID"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
