#!/usr/bin/env bash
# a Bash script that stops 4-to_infinity_and_beyond process

PID=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$PID" ]
then
	pkill --signal SIGTERM "4-to_infinity_and_beyond"
fi
