#!/usr/bin/env bash
#  a Bash script that displays To infinity and beyond indefinitely.

print_sig()
{
	echo "I am invincible!!!"
}
while :
do
	echo "To infinity and beyond"
	sleep 2
	trap print_sig SIGTERM
done
