#!/usr/bin/env bash
# script that configures an Ubuntu server by changing localhost and facebook.com Ip adress

sudo touch hosttest
echo "127.0.0.2	localhost" > hosttest
echo "8.8.8.8	facebook.com" >> hosttest
sudo cp -f hosttest /etc/hosts
